server:
  port: 8080

spring:
  application:
    name: assessment

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    export:
      prometheus:
        enabled: true